info = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(info))
print('Só tem espaços?', info.isspace())
print('É um número?', info.isnumeric())
print('É alfabético?', info.isalpha())
print('É alfanumérico?', info.isalnum())
print('Está apenas em maiusculas?', info.isupper())
print('Está apenas em minusculas?', info.islower())
print('Está capitalizada?', info.istitle())
